server:
  port: 8081

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud?connectTimeout=6000&socketTimeout=6000&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: 123456
#mybatis:
#  mapper-locations: classpath:sql/*Mapper.xml
  redis:
    host: 192.168.133.128
    port: 6379
#    cluster:
#      nodes: 192.168.133.128:6379
    database: 0
    timeout: 10000
    password: linzb1998
    #jedis:
    lettuce:
      pool:
        #最大阻塞等待时间，负数表示没有限制
        max-wait: -1
        #连接池中的最大空闲连接
        max-idle: 5
        #连接池中的最小空闲连接
        min-idle: 0
        #连接池中最大连接数，负数表示没有限
        max-active: 20
    #自定义是否开启redisson
    open-redisson: false
  #kafka
  kafka:
    #bootstrap-servers: test.mq_cep_rtc01.kafka.product.cob:6667,test.mq_cep_rtc02.kafka.product.cob:6667,test.mq_cep_rtc03.kafka.product.cob:6667
    bootstrap-servers: 192.168.133.128:9092
    producer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    consumer:
      #默认消费者组
      group-id: user
      properties:
        #消费超时时间,间隔poll最大时间,一小时
        # 使用 Kafka 消费分组机制时，再次调用 poll 允许的最大间隔。如果在该时间内没有再次调用 poll，则认为该消费者已经失败，Broker 会重新发起 Rebalance 把分配给它的 partition 分配给其他消费者
        max.poll.interval.ms: 3600000
        max.poll.records: 1
        # 使用 Kafka 消费分组机制时，消费者超时时间。当 Broker 在该时间内没有收到消费者的心跳时，认为该消费者故障失败，Broker 发起重新 Rebalance 过程。目前该值的配置必须在 Broker 配置group.min.session.timeout.ms=6000和group.max.session.timeout.ms=300000 之间
        session.timeout.ms: 60000
        # 使用 Kafka 消费分组机制时，消费者发送心跳的间隔。这个值必须小于 session.timeout.ms，一般小于它的三分之一
        heartbeat.interval.ms: 3000
      #手动提交
      enable-auto-commit: false
      auto-commit-interval: 10000
    listener:
      #offset提交,立即提交
      ack-mode: MANUAL_IMMEDIATE
      #单条消费模式
      type: single
      missing-topics-fatal: false
ftp:
  list:
    - host: 192.168.133.128
      port: 22
      username: linzb
      password: linzb
    - host: 192.168.133.128
      port: 21
      username: linzb2
      password: linzb2

sftp:
  host: 10.70.200.148 # 服务器ip
  port: 22 # ssh端口
  username: root # 用户名
  password: Fjyb@2021! # 密码
  # 连接池参数
  pool:
    max-total: 10
    max-idle: 10
    min-idle: 5

xxl-job:
  #xxjob的地址
  address: 192.168.133.128:8090/xxl-job-admin/
  #执行器的名字
  executor-appname: xx-job-linzb
  #注册的地址 自动注入可以不写
  executor-ip:
  executor-port: 8081
  accessToken:
  executor-logpath: E:\练手项目\common-log\gulu-xxljob
  executor-logretentionday: 1

sss:
  a: 555
