spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud?connectTimeout=6000&socketTimeout=6000&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
#mybatis:
#  mapper-locations: classpath:sql/*Mapper.xml
  redis:
    host: 120.25.150.153
    port: 6379
    database: 0
    timeout: 10000
    password: linzb1998
    #jedis:
    lettuce:
      pool:
        #最大阻塞等待时间，负数表示没有限制
        max-wait: -1
        #连接池中的最大空闲连接
        max-idle: 5
        #连接池中的最小空闲连接
        min-idle: 0
        #连接池中最大连接数，负数表示没有限
        max-active: 20

sss:
  a: 555
